name: Cypress Tests
on: [push]
jobs:
    cypress-run:
    runs on: ubuntu-latest
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cypress.io
      uses: cypress-io/github-action@v2
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
   
